// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4680.Eduino;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.drive.MecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainCANTalonFrontRight;
    public static CANTalon driveTrainCANTalonFrontLeft;
    public static CANTalon driveTrainCANTalonBackRight;
    public static CANTalon driveTrainCANTalonBackLeft;
    public static MecanumDrive driveTrainMecanumDrive1;
    public static AnalogGyro driveTrainGyro;
    public static DigitalInput driveTrainFrontBumperContact;
    public static CANTalon longArmArmMotorVictorSPX;
    public static CANTalon wristWristMotorVictorSPX;
    public static DigitalInput grabberCubeIsInPlace;
    public static DigitalInput grabberClimbSwitch;
    public static CANTalon grabberGrabberMotorVictorSPX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainCANTalonFrontRight = new CANTalon(0);
        LiveWindow.addActuator("Drive Train", "CANTalonFrontRight", driveTrainCANTalonFrontRight);
        
        driveTrainCANTalonFrontLeft = new CANTalon(1);
        LiveWindow.addActuator("Drive Train", "CANTalonFrontLeft", driveTrainCANTalonFrontLeft);
        
        driveTrainCANTalonBackRight = new CANTalon(2);
        LiveWindow.addActuator("Drive Train", "CAN TalonBackRight", driveTrainCANTalonBackRight);
        
        driveTrainCANTalonBackLeft = new CANTalon(3);
        LiveWindow.addActuator("Drive Train", "CANTalonBackLeft", driveTrainCANTalonBackLeft);
        
        driveTrainMecanumDrive1 = new MecanumDrive(driveTrainCANTalonFrontLeft, driveTrainCANTalonBackLeft,
              driveTrainCANTalonFrontRight, driveTrainCANTalonBackRight);
        LiveWindow.addActuator("DriveTrain", "Mecanum Drive 1", driveTrainMecanumDrive1);
        driveTrainMecanumDrive1.setSafetyEnabled(true);
        driveTrainMecanumDrive1.setExpiration(0.1);
        driveTrainMecanumDrive1.setMaxOutput(1.0);

        driveTrainGyro = new AnalogGyro(0);
        LiveWindow.addSensor("DriveTrain", "Gyro", driveTrainGyro);
        driveTrainGyro.setSensitivity(0.007);
        driveTrainFrontBumperContact = new DigitalInput(1);
        LiveWindow.addSensor("DriveTrain", "FrontBumperContact", driveTrainFrontBumperContact);
        
        longArmArmMotorVictorSPX = new CANTalon(4);
        LiveWindow.addActuator("Long Arm", "ArmMotorVictorSPX", longArmArmMotorVictorSPX);
        
        wristWristMotorVictorSPX = new CANTalon(5);
        LiveWindow.addActuator("Wrist", "WristMotorVictorSPX", wristWristMotorVictorSPX);
        
        grabberCubeIsInPlace = new DigitalInput(0);
        LiveWindow.addSensor("Grabber", "CubeIsInPlace", grabberCubeIsInPlace);
        
        grabberClimbSwitch = new DigitalInput(2);
        LiveWindow.addSensor("Grabber", "ClimbSwitch", grabberClimbSwitch);
        
        grabberGrabberMotorVictorSPX = new CANTalon(6);
        LiveWindow.addActuator("Grabber", "GrabberMotorVictorSPX", grabberGrabberMotorVictorSPX);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
